name: 'JB'

runs:
  using: 'composite'
  steps:
  - uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'temurin'

  - name: Build
    shell: bash
    run: ./mvnw --batch-mode clean verify -Pintegration-tests
    
  - name: Save artifact
    uses: actions/upload-artifact@v3
    with:
      name: spring-petclinic
      path: /home/runner/work/spring-petclinic/spring-petclinic/target/
