name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Build & upload
        uses: ./.github/workflows/composite/java-build
        
  docker-build:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Run Docker
      uses: ./.github/workflows/composite/docker
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
